apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
  labels:
    app: ${project.artifactId}
    group: ${project.groupId}
    provider: fabric8
    version: ${project.version}
spec:
  template:
    spec:
      containers:
        - env:
            - name: VIRTUAL_LAYER_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: virtual-layer-secret
                   key: username
            - name: VIRTUAL_LAYER_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: virtual-layer-secret
                   key: password
            - name: VDB_NAME
              value: "inventory"
            - name: VIRTUAL_LAYER_SERVICE_JDBC_ENDPOINT
              value: "virtual-layer.hotel-booking-virtual-layer.svc:31000"
            - name: BOOKING_STATE_SERVICE_GET_ENDPOINT
              value: "http://booking-state-service.hotel-booking-state.svc:8080/getbookingstate"
